[build]
  base = ""
  publish = "site/_site"
  command = ".ci/download_db.sh; cd site/ ; bundle install; pluto update planet.ini; ruby -r 'jekyll/planet' ruby_scripts/tool.rb; jekyll build --baseurl ''"
