# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Metadata

title: Byld
email: byld-admin@iiitd.ac.in
author: Peeyush Kushwaha, Viresh Gupta
description: >- # this means to ignore newlines until "baseurl:"
  Byld aims to bring together the community of developers within IIIT-Delhi and
  maintain a high standard / quality of devs.
  We provide newcomers a path to level up their skills and join us.
keywords: Byld, IIIT-Delhi, Software Development, Club, Programming
lang: en-IN
fb_username: byld.iiitd
github_username:  IIIT-Delhi

# Config

baseurl: "/byldWebsite" # the subpath of your site, e.g. /blog
url: "http://byld.iiitd.edu.in" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/assets/images/favicon.png"
collections:
  members:
    output: true
    permalink: /:collection/:name
defaults:
  -
    scope:
      path: ""
      type: "members"
    values:
      layout: "member-page"

# Build settings
markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
